version: '3'
services:
  db:
    image: mysql:8.0.38
    container_name: clojure-sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    volumes:
      - ./db/my.cnf:/etc/my.cnf
    platform: linux/x86_64